/**
 * Agent TOML Generator
 *
 * Generates Kimi Code CLI agent specification TOML files from
 * `AgentDefinition` records. Keeps agent configs in sync with the
 * OMK agent registry.
 *
 * Kimi Agent TOML schema (supported fields):
 *   name              - agent identifier
 *   description       - short description
 *   [model]
 *   reasoning_effort  - "low" | "medium" | "high"
 *   [prompt]
 *   system            - system prompt (markdown)
 *
 * OMK extensions (stored as comments for forward compatibility):
 *   # omk:tokenBudget  - max tokens for this agent
 *   # omk:maxSteps     - max steps per turn
 *   # omk:allowedTools - permitted tool categories
 *   # omk:modelClass   - frontier | standard | fast
 */

import { AGENT_DEFINITIONS, type AgentDefinition } from './definitions.js';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Generate a system prompt for an agent based on its definition.
 */
export function generateSystemPrompt(def: AgentDefinition): string {
  const title = def.name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  return `# Role: ${title}

${def.description}.

## OMK Configuration
- Model Class: ${def.modelClass}
- Reasoning Effort: ${def.reasoningEffort}
- Token Budget: ${(def.tokenBudget ?? 32_000).toLocaleString()}
- Max Steps: ${def.maxSteps ?? 30}
- Allowed Tools: ${Array.isArray(def.allowedTools) ? def.allowedTools.join(', ') : 'all'}

## Mission
Execute the assigned task with the configured resource constraints.
Respect tool restrictions and stay within the token budget.
Report completion with evidence via \`omk_submit_evidence\`.
`;
}

/**
 * Generate a TOML string for a single agent definition.
 */
export function generateAgentTOML(def: AgentDefinition): string {
  const lines: string[] = [
    '# Native agent config for Kimi Code CLI',
    '# Generated by omk-cli',
    '',
    `name = "${def.name}"`,
    `description = "${def.description}"`,
    '',
    '# OMK metadata extensions',
    `# omk:modelClass = "${def.modelClass}"`,
    `# omk:tokenBudget = ${def.tokenBudget ?? 32_000}`,
    `# omk:maxSteps = ${def.maxSteps ?? 30}`,
    `# omk:allowedTools = "${Array.isArray(def.allowedTools) ? def.allowedTools.join(',') : 'all'}"`,
    '',
    '[model]',
    `reasoning_effort = "${def.reasoningEffort}"`,
    '',
    '[prompt]',
    'system = """',
    generateSystemPrompt(def).trim(),
    '"""',
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate TOML strings for all registered agents.
 */
export function generateAllAgentTOMLs(): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, def] of Object.entries(AGENT_DEFINITIONS)) {
    result[key] = generateAgentTOML(def);
  }
  return result;
}

/**
 * Write all agent TOML files to a target directory.
 *
 * @param targetDir - e.g., ~/.kimi/agents
 * @returns Array of written file paths
 */
export function writeAgentTOMLs(targetDir: string): string[] {
  mkdirSync(targetDir, { recursive: true });
  const all = generateAllAgentTOMLs();
  const written: string[] = [];

  for (const [key, content] of Object.entries(all)) {
    const filePath = join(targetDir, `${key}.toml`);
    writeFileSync(filePath, content, 'utf-8');
    written.push(filePath);
  }

  return written;
}

/**
 * Get a summary of what would be written without actually writing.
 */
export function previewAgentTOMLs(): Array<{
  name: string;
  reasoningEffort: string;
  tokenBudget: number;
  maxSteps: number;
  tools: string;
}> {
  return Object.values(AGENT_DEFINITIONS).map((def) => ({
    name: def.name,
    reasoningEffort: def.reasoningEffort,
    tokenBudget: def.tokenBudget ?? 32_000,
    maxSteps: def.maxSteps ?? 30,
    tools: Array.isArray(def.allowedTools) ? def.allowedTools.join(',') : 'all',
  }));
}
